/**
 * Agent Context
 * Container for request context, constraints, and accumulated state
 */

import { randomUUID } from 'crypto';

/**
 * Lifecycle stages
 */
export const Stage = {
    INIT: 'INIT',
    PERCEIVE: 'PERCEIVE',
    THINK: 'THINK',
    PLAN: 'PLAN',
    PROPOSE: 'PROPOSE_DECISION',
    REFLECT: 'REFLECT',
    COMPLETE: 'COMPLETE',
    ERROR: 'ERROR',
};

/**
 * Context class - immutable request context container
 */
export class Context {
    /**
     * @param {Object} params
     * @param {string} params.query - User query
     * @param {Object} params.constraints - Pre-decision constraints
     * @param {Object} params.decisionPolicy - CEO decision policy
     * @param {Object} params.contextPolicy - RAG context policy
     */
    constructor({ query, constraints = {}, decisionPolicy = {}, contextPolicy = {} }) {
        // Immutable ID and timestamp
        this.id = randomUUID();
        this.createdAt = new Date().toISOString();

        // Input
        this.query = query;

        // Policies (frozen to prevent mutation)
        this.decisionPolicy = Object.freeze({ ...decisionPolicy });
        this.contextPolicy = Object.freeze({ ...contextPolicy });

        // Pre-decision constraints from human
        this.constraints = Object.freeze({
            budgetLimit: constraints.budgetLimit ?? null,
            timeHorizon: constraints.timeHorizon ?? null,
            ethicalBoundaries: constraints.ethicalBoundaries ?? [],
            mustInclude: constraints.mustInclude ?? [],
            mustExclude: constraints.mustExclude ?? [],
            ...constraints,
        });

        // Mutable state (accumulated during lifecycle)
        this._state = {
            stage: Stage.INIT,
            iteration: 0,
            memory: [],
            ragContext: [],
            options: [],
            evaluations: [],
            risks: {},
            proposal: null,
            confidence: null,
            assumptions: [],
            missingData: [],
            errors: [],
            auditLog: [],
        };
    }

    // ─────────────────────────────────────────────────────────────
    // Stage Management
    // ─────────────────────────────────────────────────────────────

    get stage() {
        return this._state.stage;
    }

    setStage(stage) {
        this._logAudit('stage_change', { from: this._state.stage, to: stage });
        this._state.stage = stage;
    }

    get iteration() {
        return this._state.iteration;
    }

    incrementIteration() {
        this._state.iteration += 1;
        this._logAudit('iteration_increment', { iteration: this._state.iteration });
    }

    // ─────────────────────────────────────────────────────────────
    // Memory Context
    // ─────────────────────────────────────────────────────────────

    get memory() {
        return [...this._state.memory];
    }

    addMemory(memoryItems) {
        this._state.memory.push(...memoryItems);
        this._logAudit('memory_added', { count: memoryItems.length });
    }

    // ─────────────────────────────────────────────────────────────
    // RAG Context
    // ─────────────────────────────────────────────────────────────

    get ragContext() {
        return [...this._state.ragContext];
    }

    addRagContext(documents) {
        this._state.ragContext.push(...documents);
        this._logAudit('rag_context_added', { count: documents.length });
    }

    // ─────────────────────────────────────────────────────────────
    // Options (generated by LLM)
    // ─────────────────────────────────────────────────────────────

    get options() {
        return [...this._state.options];
    }

    setOptions(options) {
        this._state.options = options;
        this._logAudit('options_generated', { count: options.length });
    }

    // ─────────────────────────────────────────────────────────────
    // Evaluations (deterministic scoring)
    // ─────────────────────────────────────────────────────────────

    get evaluations() {
        return [...this._state.evaluations];
    }

    setEvaluations(evaluations) {
        this._state.evaluations = evaluations;
        this._logAudit('options_evaluated', { count: evaluations.length });
    }

    // ─────────────────────────────────────────────────────────────
    // Risk Assessment
    // ─────────────────────────────────────────────────────────────

    get risks() {
        return { ...this._state.risks };
    }

    setRisks(risks) {
        this._state.risks = risks;
        this._logAudit('risks_assessed', { riskTypes: Object.keys(risks) });
    }

    // ─────────────────────────────────────────────────────────────
    // Proposal Output
    // ─────────────────────────────────────────────────────────────

    get proposal() {
        return this._state.proposal;
    }

    setProposal(proposal) {
        this._state.proposal = proposal;
        this._logAudit('proposal_created', {
            hasRecommendation: !!proposal.recommendation,
            confidence: proposal.confidence,
        });
    }

    // ─────────────────────────────────────────────────────────────
    // Confidence & Assumptions
    // ─────────────────────────────────────────────────────────────

    get confidence() {
        return this._state.confidence;
    }

    setConfidence(confidence) {
        this._state.confidence = confidence;
    }

    get assumptions() {
        return [...this._state.assumptions];
    }

    addAssumptions(assumptions) {
        this._state.assumptions.push(...assumptions);
    }

    get missingData() {
        return [...this._state.missingData];
    }

    addMissingData(fields) {
        this._state.missingData.push(...fields);
        this._logAudit('missing_data_identified', { fields });
    }

    // ─────────────────────────────────────────────────────────────
    // Error Handling
    // ─────────────────────────────────────────────────────────────

    get errors() {
        return [...this._state.errors];
    }

    addError(error) {
        this._state.errors.push({
            message: error.message,
            code: error.code,
            timestamp: new Date().toISOString(),
        });
        this._logAudit('error_occurred', { code: error.code, message: error.message });
    }

    // ─────────────────────────────────────────────────────────────
    // Audit Log
    // ─────────────────────────────────────────────────────────────

    get auditLog() {
        return [...this._state.auditLog];
    }

    _logAudit(action, details = {}) {
        this._state.auditLog.push({
            action,
            details,
            timestamp: new Date().toISOString(),
            stage: this._state.stage,
            iteration: this._state.iteration,
        });
    }

    // ─────────────────────────────────────────────────────────────
    // Serialization
    // ─────────────────────────────────────────────────────────────

    toJSON() {
        return {
            id: this.id,
            createdAt: this.createdAt,
            query: this.query,
            constraints: this.constraints,
            stage: this._state.stage,
            iteration: this._state.iteration,
            proposal: this._state.proposal,
            confidence: this._state.confidence,
            assumptions: this._state.assumptions,
            missingData: this._state.missingData,
            errors: this._state.errors,
            auditLog: this._state.auditLog,
        };
    }
}

export default Context;
